[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "histo"
version = "0.1.0"

[[bin]]
name = "histo"
doc = false

[dependencies]
streaming-stats = "0.1.28"

[dependencies.quickcheck]
optional = true
version = "0.4.1"
